# config.yml - 深度学习模型超参数配置文件

# 模型配置
model:
  architecture: "ResNet50"  # 模型架构
  pretrained: true  # 是否使用预训练模型
  num_classes: 10  # 输出类别数

# 数据配置
data:
  batch_size: 32  # 每批次的样本数
  image_size: 224  # 输入图像的尺寸
  train_data_path: "/data/train"  # 训练数据路径
  val_data_path: "/data/val"  # 验证数据路径
  num_workers: 4  # 数据加载时的线程数

# 优化器配置
optimizer:
  type: "Adam"  # 优化器类型
  learning_rate: 0.001  # 学习率
  weight_decay: 0.0001  # 权重衰减
  betas: [0.9, 0.999]  # Adam优化器的beta值

# 损失函数配置
loss:
  type: "CrossEntropyLoss"  # 损失函数类型

# 训练配置
train:
  epochs: 50  # 训练轮数
  save_checkpoint: true  # 是否保存检查点
  checkpoint_interval: 5  # 每5轮保存一次检查点
  early_stopping_patience: 10  # 早停策略：如果10轮没有提升，则停止训练

# 学习率调度器配置
scheduler:
  type: "StepLR"  # 学习率调度器类型
  step_size: 10  # 每10轮学习率衰减一次
  gamma: 0.5  # 学习率衰减倍数

# 设备配置
device:
  use_gpu: true  # 是否使用GPU
  gpu_id: 0  # GPU编号
